# Mind Mapr Backend Configuration
spring.application.name=mindmapr-backend

# Server Port
server.port=8080

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174,http://localhost:3000

management.endpoint.health.show-details=always


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mindmapr
spring.datasource.username=root
spring.datasource.password=Shivaprasad5474

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info